// File: buildao.h

#ifndef buildao_h
#define buildao_h

/* Pi^3 (From mathematica) */
#define M_PI_3 31.0062766802998201

/*
 * ao_basisfunc: an atomic orbital basis function
 */
struct ao_basisfunc {
        int type; /* s=1,px=2,py=3,pz=4,d2-=5,d1-=6,d0=7,
                   * d1+=8,d2+=9,f3-=10,f2-=11,f1-=12,... */
        int lval;
        int mval;
        int ugaus;      /* Uncontracted gaussians */
        double *ccoef;  /* Contraction coefficients */
        double *alpha;  /* alpha coefficients */
        int atom;       /* Center index */
        double *geom;   /* Center geometry */
        double gscale;  /* Gaussian scaling */
};


/*
 * ao_basis: atomic orbital basis information.
 */
struct ao_basis {
        int ugaus;      /* uncontracted gaussians */
        int cgaus;      /* contracted gaussians */
        double *alpha;  /* alpha values */
        double **ccoef; /* contraction coefficients. Stored: M[cgaus][ugaus] */      
};
        
/*
 * ao_atomdata: atom data for atomic orbitals 
 */
struct ao_atomdata {
        char name[2];           /* Atom name */
        double nucchrg;         /* Nuclear charge */
        int natm;               /* Number of atoms in type. */
        int maxlval;            /* Maximum l value */
        int *naob;              /* Number of aoblocks per l value */
        double **geom;          /* atom geometries */
        int totblk;             /* total number of ao blocks */
        int *lval;              /* lvalues for each block: s = 0, p = 1, etc */
        struct ao_basis *basis; /* Basis information for each block */
};

/*
 * ao_buildao: build atomic orbitals.
 */
int ao_buildao();

/*
 * ao_build_atomic_orbitalset: build atomic orbital basis set from adata.
 * This routine will build the array (struct ao_basisfunc) aobasis. AOBASIS
 * will hold l, m, contraction information, and geometry information. This
 * routine requires the soinfo.dat generated by DALTON.
 */
int ao_build_atomic_orbitalset(
        struct ao_atomdata *adata,
        struct ao_basisfunc *aobasis,
        int atypes,
        int *norbs);

/*
 * ao_check_for_daltaoin: Check for daltaoin file.
 */
int ao_check_for_daltaoin();

/*
 * ao_check_for_soinfodat: Check for soinfo.dat file.
 */
int ao_check_for_soinfodat();

/*
 * ao_cp_alphavals_ccoefs: copy alpha values and contraction coefficients for
 * ao block and contracted gaussian.
 */
void ao_cp_alphavals_ccoefs(
        int block,
        int gauss,
        struct ao_atomdata adata,
        struct ao_basisfunc *aobasis);


/*
 * ao_cp_gaussian_scaling: copy gaussian scaling constant into new orbital.
 */
void ao_cp_gaussian_scaling(
        struct ao_basisfunc *bas,
        double *gscal,
        int *norb_per_l,
        int lval);

/*
 * ao_get_gscalings: get gaussian scalings from soinfo.dat file.
 */
int ao_get_gscalings(
        FILE *soinfo,
        double **gscal,
        int *ngaus);

/*
 * ao_get_atominfo: get atominfo character arrays from soinfo.dat file.
 */
int ao_get_atominfo(
        FILE *soinfo,
        char ***ainfo,
        int *natoms);

/*
 * ao_get_block_and_gauss_number: get block number and contracted gaussian
 * number from the current orbital.
 */
void ao_get_block_and_gauss_number(
        int *norbpl,
        struct ao_atomdata adata,
        int lvalue,
        int *blockn,
        int *gaussn);

        
/*
 * ao_get_lvalue_from_type: get lvalue from the orbital type.
 * 0 = s(1), 1 = p(2,3,4), 2 = d(5,6,7,8,9), 3 = f(10,11,12,13,14,15,16),...
 */
int ao_get_lvalue_from_type(
        int oindex);


/*
 * ao_get_orbitalnum: get orbital number of soinfo.dat file.
 */
int ao_get_orbitalnum(
        FILE *soinfo,
        int *norbs);

/*
 * ao_increment_norb_per_l: increment number of orbital per l value if
 * px, d2-, etc.
 */
void ao_increment_norb_per_l(
        int *nopl,
        int oindex);

/*
 * ao_initialize_atomic_orbital_set: initialize atomic orbital array.
 */
struct ao_basisfunc *ao_initialize_atomic_orbital_set(
        int norbs);

/*
 * ao_open_daltonfile: open dalton file returing file stream.
 */
FILE *ao_open_daltonfile(
        FILE *daltin); /* Dalton input file stream */

/*
 * ao_open_soinfodat: open soinfo.dat file, returning file stream.
 */
FILE *ao_open_soinfodat(
        FILE *soinfo);

/*
 * ao_read_daltontitle: read first three lines of daltaoin file.
 * INTGRL
 * X
 * X
 */
int ao_read_daltontitle(
        FILE *daltin); /* Dalton input file stream */

/*
 * ao_read_dalton_atombasis1: read first line of atom basis set iformation.
 * (Reads in: nuclear charge, number of atoms, max L value, blocks per L value
 */
int ao_read_dalton_atombasis1(
        FILE *daltin,
        struct ao_atomdata *adata);

/*
 * ao_read_dalton_atombasis2: read atomic orbital basis blocks from daltaoin
 * file into the AO_ATOMDATA.AO_ABASIS type.
 */
int ao_read_dalton_atombasis2(
        FILE *daltin,
        struct ao_atomdata *adata);

/*
 * ao_print_dalton_basisinfo1: print first line of values read from daltaoin.
 */
void ao_print_dalton_basisinfo1(
        char      *crt, /* spherical harmonics flag */
        int     atypes, /* Unique atom types */
        int     molchg, /* Molecular charge */
        char   *symtxt, /* symmetry operations test */
        double    thrs);/* integralthreshold */

/*
 * ao_print_dalton_atombasis1(adata)
 */
void ao_print_dalton_atombasis1(
        struct ao_atomdata adata);

/*
 * ao_print_orbital_information: print final atomic orbital information.
 */
void ao_print_orbital_information(
        struct ao_basisfunc aobasis);

/*
 * ao_process_aorbital_dataline: process atomic orbital data line from
 * soinfo.dat. This line describes the orbital type in the atomic orbital
 * ordering.
 */
void ao_process_aorbital_dataline(char *line, int *anum, char *atom,
                                  int *atype_anum, int *onum, char *ao_desc,
                                  int *oindex, char *atom_desc);

/*
 * ao_process_orbitaldata: process atomic orbital data, generating an array of
 * atomic orbitals.
 */
int ao_process_orbitaldata(
        struct ao_atomdata *adata,
        struct ao_basisfunc *aobasis,
        FILE *soinfo,
        int norbs,
        double *gscal,
        int ngaus,
        char **atominfo,
        int atypes);


/*
 * ao_read_dalton_basisinfo1: read first line of basis set information in
 * dalton file.
 */
int ao_read_dalton_basisinfo1(
        FILE *daltin, 
        char    *crt,
        int  *atypes,
        int  *molchg,
        char *symtxt,
        double *thrs,
        char    *id3);
/*
 * ao_read_dalton_contractionvals: read contraction values for a uncontracted
 * gaussian.
 */
int ao_read_dalton_contractionvals(
        FILE *daltin,
        struct ao_basis *basis,
        int ug);

#endif
