        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:53:05 2014
        MODULE CANNON__genmod
          INTERFACE 
            SUBROUTINE CANNON(STRING,LENGTH,PERMIND)
              INTEGER(KIND=8), INTENT(IN) :: LENGTH
              INTEGER(KIND=8) :: STRING(LENGTH)
              INTEGER(KIND=8), INTENT(OUT) :: PERMIND
            END SUBROUTINE CANNON
          END INTERFACE 
        END MODULE CANNON__genmod
