        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:53:05 2014
        MODULE CANNONREAL__genmod
          INTERFACE 
            SUBROUTINE CANNONREAL(STRING,LENGTH,PERMIND)
              INTEGER(KIND=8), INTENT(IN) :: LENGTH
              REAL(KIND=8) :: STRING(LENGTH)
              INTEGER(KIND=8), INTENT(OUT) :: PERMIND
            END SUBROUTINE CANNONREAL
          END INTERFACE 
        END MODULE CANNONREAL__genmod
