        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:53:04 2014
        MODULE CITRUNC__genmod
          INTERFACE 
            SUBROUTINE CITRUNC(ADETS,BDETS,AELEC,BELEC,ORBITALS,NFROZEN,&
     &NDOCC,NACTIVE,XLEVEL,MODALPHALEN,MODBETALEN,CIDIMENSION,UNIT1,    &
     &UNIT2,UNIT3,UNIT4,UNIT5,UNIT6,UNIT7,UNIT8,UNIT9,UNIT10)
              INTEGER(KIND=8), INTENT(IN) :: BELEC
              INTEGER(KIND=8), INTENT(IN) :: AELEC
              INTEGER(KIND=8), INTENT(IN) :: BDETS
              INTEGER(KIND=8), INTENT(IN) :: ADETS
              INTEGER(KIND=8), INTENT(IN) :: ORBITALS
              INTEGER(KIND=8), INTENT(IN) :: NFROZEN
              INTEGER(KIND=8), INTENT(IN) :: NDOCC
              INTEGER(KIND=8), INTENT(IN) :: NACTIVE
              INTEGER(KIND=8), INTENT(IN) :: XLEVEL
              INTEGER(KIND=8) :: MODALPHALEN
              INTEGER(KIND=8) :: MODBETALEN
              INTEGER(KIND=8) :: CIDIMENSION
              INTEGER(KIND=8), INTENT(IN) :: UNIT1
              INTEGER(KIND=8), INTENT(IN) :: UNIT2
              INTEGER(KIND=8), INTENT(IN) :: UNIT3
              INTEGER(KIND=8), INTENT(IN) :: UNIT4
              INTEGER(KIND=8), INTENT(IN) :: UNIT5
              INTEGER(KIND=8), INTENT(IN) :: UNIT6
              INTEGER(KIND=8), INTENT(IN) :: UNIT7
              INTEGER(KIND=8), INTENT(IN) :: UNIT8
              INTEGER(KIND=8), INTENT(IN) :: UNIT9
              INTEGER(KIND=8), INTENT(IN) :: UNIT10
            END SUBROUTINE CITRUNC
          END INTERFACE 
        END MODULE CITRUNC__genmod
