        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:53:06 2014
        MODULE DAVIDSON__genmod
          INTERFACE 
            SUBROUTINE DAVIDSON(INITGDIM,INIT_VECTORS,DIAGONALS,MOINTS1,&
     &MOINTS1LEN,MOINTS2,MOINTS2LEN,CIDIM,PSTRING,PSTEP,PLOCATE,QSTRING,&
     &QSTEP,QLOCATE,XREFLIST,PDETS,PDETSLEN,QDETS,QDETSLEN,ADETS,BDETS, &
     &AELEC,BELEC,ORBITALS,KRMIN,KRMAX,RTOL,ROOTS,MAX_ITER,EIGVALUES,   &
     &EIGVECTORS)
              INTEGER(KIND=8), INTENT(IN) :: ROOTS
              INTEGER(KIND=8), INTENT(IN) :: KRMAX
              INTEGER(KIND=8), INTENT(IN) :: QDETSLEN
              INTEGER(KIND=8), INTENT(IN) :: PDETSLEN
              INTEGER(KIND=8), INTENT(IN) :: CIDIM
              INTEGER(KIND=8), INTENT(IN) :: MOINTS2LEN
              INTEGER(KIND=8), INTENT(IN) :: MOINTS1LEN
              INTEGER(KIND=8), INTENT(IN) :: INITGDIM
              REAL(KIND=8), INTENT(IN) :: INIT_VECTORS(CIDIM,INITGDIM)
              REAL(KIND=8), INTENT(IN) :: DIAGONALS(CIDIM)
              REAL(KIND=8), INTENT(IN) :: MOINTS1(MOINTS1LEN)
              REAL(KIND=8), INTENT(IN) :: MOINTS2(MOINTS2LEN)
              INTEGER(KIND=8), INTENT(IN) :: PSTRING(CIDIM,2)
              INTEGER(KIND=8), INTENT(IN) :: PSTEP(PDETSLEN)
              INTEGER(KIND=8), INTENT(IN) :: PLOCATE(PDETSLEN)
              INTEGER(KIND=8), INTENT(IN) :: QSTRING(CIDIM,2)
              INTEGER(KIND=8), INTENT(IN) :: QSTEP(QDETSLEN)
              INTEGER(KIND=8), INTENT(IN) :: QLOCATE(QDETSLEN)
              INTEGER(KIND=8), INTENT(IN) :: XREFLIST(CIDIM)
              INTEGER(KIND=8), INTENT(IN) :: PDETS(PDETSLEN)
              INTEGER(KIND=8), INTENT(IN) :: QDETS(QDETSLEN)
              INTEGER(KIND=8), INTENT(IN) :: ADETS
              INTEGER(KIND=8), INTENT(IN) :: BDETS
              INTEGER(KIND=8), INTENT(IN) :: AELEC
              INTEGER(KIND=8), INTENT(IN) :: BELEC
              INTEGER(KIND=8), INTENT(IN) :: ORBITALS
              INTEGER(KIND=8), INTENT(IN) :: KRMIN
              REAL(KIND=8), INTENT(IN) :: RTOL
              INTEGER(KIND=8), INTENT(IN) :: MAX_ITER
              REAL(KIND=8), INTENT(OUT) :: EIGVALUES(ROOTS)
              REAL(KIND=8), INTENT(OUT) :: EIGVECTORS(CIDIM,ROOTS)
            END SUBROUTINE DAVIDSON
          END INTERFACE 
        END MODULE DAVIDSON__genmod
