        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:53:05 2014
        MODULE DOUBLEREPINFO__genmod
          INTERFACE 
            SUBROUTINE DOUBLEREPINFO(STRING1,STR1LEN,NEWORB1,INDXSWP1,  &
     &NEWORB2,INDXSWP2,ORBITALS,EPS1,INDX)
              INTEGER(KIND=8), INTENT(IN) :: STR1LEN
              INTEGER(KIND=8) :: STRING1(STR1LEN)
              INTEGER(KIND=8), INTENT(IN) :: NEWORB1
              INTEGER(KIND=8), INTENT(IN) :: INDXSWP1
              INTEGER(KIND=8), INTENT(IN) :: NEWORB2
              INTEGER(KIND=8), INTENT(IN) :: INDXSWP2
              INTEGER(KIND=8), INTENT(IN) :: ORBITALS
              INTEGER(KIND=8) :: EPS1
              INTEGER(KIND=8) :: INDX
            END SUBROUTINE DOUBLEREPINFO
          END INTERFACE 
        END MODULE DOUBLEREPINFO__genmod
