        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:53:05 2014
        MODULE LOWDIAGS__genmod
          INTERFACE 
            SUBROUTINE LOWDIAGS(VECTOR1,LENGTH,CHOOSE,INITGUESS)
              INTEGER(KIND=8), INTENT(IN) :: CHOOSE
              INTEGER(KIND=8), INTENT(IN) :: LENGTH
              REAL(KIND=8) :: VECTOR1(LENGTH)
              REAL(KIND=8), INTENT(OUT) :: INITGUESS(LENGTH,CHOOSE)
            END SUBROUTINE LOWDIAGS
          END INTERFACE 
        END MODULE LOWDIAGS__genmod
