        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:53:05 2014
        MODULE SINGREPINFO__genmod
          INTERFACE 
            SUBROUTINE SINGREPINFO(STRING1,STR1LEN,NEWORB,INDXSWP,      &
     &ORBITALS,EPS1,INDX)
              INTEGER(KIND=8), INTENT(IN) :: STR1LEN
              INTEGER(KIND=8) :: STRING1(STR1LEN)
              INTEGER(KIND=8), INTENT(IN) :: NEWORB
              INTEGER(KIND=8), INTENT(IN) :: INDXSWP
              INTEGER(KIND=8), INTENT(IN) :: ORBITALS
              INTEGER(KIND=8) :: EPS1
              INTEGER(KIND=8) :: INDX
            END SUBROUTINE SINGREPINFO
          END INTERFACE 
        END MODULE SINGREPINFO__genmod
