        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 24 17:34:46 2014
        MODULE ACTHV__genmod
          INTERFACE 
            SUBROUTINE ACTHV(VECTOR1,MOINTS1,MOINTS2,MOINTS1LEN,        &
     &MOINTS2LEN,PSTRING,PSTEP,PLOCATE,QSTRING,QSTEP,QLOCATE,XREFLIST,  &
     &CIDIM,PDETS,QDETS,PDETSTRUNC,QDETSTRUNC,ADETS,BDETS,AELEC,BELEC,  &
     &ORBITALS,DIAGONALS,VECTOR2)
              INTEGER(KIND=8), INTENT(IN) :: QDETSTRUNC
              INTEGER(KIND=8), INTENT(IN) :: PDETSTRUNC
              INTEGER(KIND=8), INTENT(IN) :: CIDIM
              INTEGER(KIND=8), INTENT(IN) :: MOINTS2LEN
              INTEGER(KIND=8), INTENT(IN) :: MOINTS1LEN
              REAL(KIND=8), INTENT(IN) :: VECTOR1(CIDIM)
              REAL(KIND=8), INTENT(IN) :: MOINTS1(MOINTS1LEN)
              REAL(KIND=8), INTENT(IN) :: MOINTS2(MOINTS2LEN)
              INTEGER(KIND=8), INTENT(IN) :: PSTRING(CIDIM,2)
              INTEGER(KIND=8), INTENT(IN) :: PSTEP(PDETSTRUNC)
              INTEGER(KIND=8), INTENT(IN) :: PLOCATE(PDETSTRUNC)
              INTEGER(KIND=8), INTENT(IN) :: QSTRING(CIDIM,2)
              INTEGER(KIND=8), INTENT(IN) :: QSTEP(QDETSTRUNC)
              INTEGER(KIND=8), INTENT(IN) :: QLOCATE(QDETSTRUNC)
              INTEGER(KIND=8), INTENT(IN) :: XREFLIST(CIDIM)
              INTEGER(KIND=8), INTENT(IN) :: PDETS(PDETSTRUNC)
              INTEGER(KIND=8), INTENT(IN) :: QDETS(QDETSTRUNC)
              INTEGER(KIND=8), INTENT(IN) :: ADETS
              INTEGER(KIND=8), INTENT(IN) :: BDETS
              INTEGER(KIND=8), INTENT(IN) :: AELEC
              INTEGER(KIND=8), INTENT(IN) :: BELEC
              INTEGER(KIND=8), INTENT(IN) :: ORBITALS
              REAL(KIND=8), INTENT(IN) :: DIAGONALS(CIDIM)
              REAL(KIND=8), INTENT(INOUT) :: VECTOR2(CIDIM)
            END SUBROUTINE ACTHV
          END INTERFACE 
        END MODULE ACTHV__genmod
