        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 24 17:34:45 2014
        MODULE CANNON__genmod
          INTERFACE 
            SUBROUTINE CANNON(STRING,LENGTH,PERMIND)
              INTEGER(KIND=8), INTENT(IN) :: LENGTH
              INTEGER(KIND=8), INTENT(INOUT) :: STRING(LENGTH)
              INTEGER(KIND=8), INTENT(OUT) :: PERMIND
            END SUBROUTINE CANNON
          END INTERFACE 
        END MODULE CANNON__genmod
