        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 24 17:34:46 2014
        MODULE CONTRIBDIAG__genmod
          INTERFACE 
            SUBROUTINE CONTRIBDIAG(SPIN,DETLIST,DETLISTLEN,PSTRING,     &
     &PSTRINGLEN,QSTRING,QSTRINGLEN,PSTEP,PSTEPLEN,QSTEP,QSTEPLEN,AELEC,&
     &BELEC,ORBITALS,ADETS,BDETS,PDETS,PDETSLEN,QDETS,QDETSLEN,MOINTS1, &
     &MOINTS1LEN,MOINTS2,MOINTS2LEN,PXREFLIST,QXREFLIST,XREFLISTLEN,    &
     &PLOCATE,QLOCATE,DIAGONALS)
              INTEGER(KIND=8), INTENT(IN) :: XREFLISTLEN
              INTEGER(KIND=8), INTENT(IN) :: MOINTS2LEN
              INTEGER(KIND=8), INTENT(IN) :: MOINTS1LEN
              INTEGER(KIND=8), INTENT(IN) :: QDETSLEN
              INTEGER(KIND=8), INTENT(IN) :: PDETSLEN
              INTEGER(KIND=8), INTENT(IN) :: BELEC
              INTEGER(KIND=8), INTENT(IN) :: AELEC
              INTEGER(KIND=8), INTENT(IN) :: QSTEPLEN
              INTEGER(KIND=8), INTENT(IN) :: PSTEPLEN
              INTEGER(KIND=8), INTENT(IN) :: QSTRINGLEN
              INTEGER(KIND=8), INTENT(IN) :: PSTRINGLEN
              INTEGER(KIND=8), INTENT(IN) :: DETLISTLEN
              CHARACTER(LEN=1), INTENT(IN) :: SPIN
              INTEGER(KIND=8), INTENT(IN) :: DETLIST(DETLISTLEN)
              INTEGER(KIND=8), INTENT(IN) :: PSTRING(PSTRINGLEN,2)
              INTEGER(KIND=8), INTENT(IN) :: QSTRING(QSTRINGLEN,2)
              INTEGER(KIND=8), INTENT(IN) :: PSTEP(PSTEPLEN)
              INTEGER(KIND=8), INTENT(IN) :: QSTEP(QSTEPLEN)
              INTEGER(KIND=8), INTENT(IN) :: ORBITALS
              INTEGER(KIND=8), INTENT(IN) :: ADETS
              INTEGER(KIND=8), INTENT(IN) :: BDETS
              INTEGER(KIND=8), INTENT(IN) :: PDETS(PDETSLEN)
              INTEGER(KIND=8), INTENT(IN) :: QDETS(QDETSLEN)
              REAL(KIND=8), INTENT(IN) :: MOINTS1(MOINTS1LEN)
              REAL(KIND=8), INTENT(IN) :: MOINTS2(MOINTS2LEN)
              INTEGER(KIND=8), INTENT(IN) :: PXREFLIST(XREFLISTLEN)
              INTEGER(KIND=8), INTENT(IN) :: QXREFLIST(XREFLISTLEN)
              INTEGER(KIND=8), INTENT(IN) :: PLOCATE(PSTEPLEN)
              INTEGER(KIND=8), INTENT(IN) :: QLOCATE(QSTEPLEN)
              REAL(KIND=8), INTENT(INOUT) :: DIAGONALS(DETLISTLEN)
            END SUBROUTINE CONTRIBDIAG
          END INTERFACE 
        END MODULE CONTRIBDIAG__genmod
