        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 24 17:34:46 2014
        MODULE DIAGONAL__genmod
          INTERFACE 
            SUBROUTINE DIAGONAL(PSTRING,PSTEP,PSTEPLEN,QSTRING,QSTEP,   &
     &QSTEPLEN,PDETS,PDETSLEN,QDETS,QDETSLEN,DETLIST,CIDIM,TOTELS,      &
     &ORBITALS,AELEC,BELEC,ADETS,BDETS,MOINTS1,MOINTS1LEN,MOINTS2,      &
     &MOINTS2LEN,PLOCATE,QLOCATE,DIAGONALS)
              INTEGER(KIND=8), INTENT(IN) :: MOINTS2LEN
              INTEGER(KIND=8), INTENT(IN) :: MOINTS1LEN
              INTEGER(KIND=8), INTENT(IN) :: CIDIM
              INTEGER(KIND=8), INTENT(IN) :: QDETSLEN
              INTEGER(KIND=8), INTENT(IN) :: PDETSLEN
              INTEGER(KIND=8), INTENT(IN) :: QSTEPLEN
              INTEGER(KIND=8), INTENT(IN) :: PSTEPLEN
              INTEGER(KIND=8), INTENT(IN) :: PSTRING(CIDIM,2)
              INTEGER(KIND=8), INTENT(IN) :: PSTEP(PSTEPLEN)
              INTEGER(KIND=8), INTENT(IN) :: QSTRING(CIDIM,2)
              INTEGER(KIND=8), INTENT(IN) :: QSTEP(QSTEPLEN)
              INTEGER(KIND=8), INTENT(IN) :: PDETS(PDETSLEN)
              INTEGER(KIND=8), INTENT(IN) :: QDETS(QDETSLEN)
              INTEGER(KIND=8), INTENT(IN) :: DETLIST(CIDIM)
              INTEGER(KIND=8), INTENT(IN) :: TOTELS
              INTEGER(KIND=8), INTENT(IN) :: ORBITALS
              INTEGER(KIND=8), INTENT(IN) :: AELEC
              INTEGER(KIND=8), INTENT(IN) :: BELEC
              INTEGER(KIND=8), INTENT(IN) :: ADETS
              INTEGER(KIND=8), INTENT(IN) :: BDETS
              REAL(KIND=8), INTENT(IN) :: MOINTS1(MOINTS1LEN)
              REAL(KIND=8), INTENT(IN) :: MOINTS2(MOINTS2LEN)
              INTEGER(KIND=8), INTENT(IN) :: PLOCATE(PSTEPLEN)
              INTEGER(KIND=8), INTENT(IN) :: QLOCATE(QSTEPLEN)
              REAL(KIND=8), INTENT(INOUT) :: DIAGONALS(CIDIM)
            END SUBROUTINE DIAGONAL
          END INTERFACE 
        END MODULE DIAGONAL__genmod
