        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 24 17:34:46 2014
        MODULE FORMDIAGINDEXES__genmod
          INTERFACE 
            SUBROUTINE FORMDIAGINDEXES(STRING,LENGTH,BELEC,ORBITALS,    &
     &INDEXSTRING)
              INTEGER(KIND=8), INTENT(IN) :: LENGTH
              INTEGER(KIND=8), INTENT(IN) :: STRING(LENGTH,2)
              INTEGER(KIND=8), INTENT(IN) :: BELEC
              INTEGER(KIND=8), INTENT(IN) :: ORBITALS
              INTEGER(KIND=8), INTENT(OUT) :: INDEXSTRING(LENGTH)
            END SUBROUTINE FORMDIAGINDEXES
          END INTERFACE 
        END MODULE FORMDIAGINDEXES__genmod
