        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 24 17:34:45 2014
        MODULE POSSEX1__genmod
          INTERFACE 
            SUBROUTINE POSSEX1(STRING,ORBITALS,ELECTRONS,PEXITSLEN,     &
     &PEXITS)
              INTEGER(KIND=8), INTENT(IN) :: PEXITSLEN
              INTEGER(KIND=8), INTENT(IN) :: ELECTRONS
              INTEGER(KIND=8), INTENT(IN) :: ORBITALS
              INTEGER(KIND=8) :: STRING(ELECTRONS)
              INTEGER(KIND=8) :: PEXITS(PEXITSLEN)
            END SUBROUTINE POSSEX1
          END INTERFACE 
        END MODULE POSSEX1__genmod
